server:
  port: 80
  servlet:

    context-path: /sgai

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/project?characterEncoding=utf8&nullCatalogMeansCurrent=true&useSSL=false&useUnicode=true&0=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


mybatis:
  cache-enabled: true
  type-aliases-package: com.mybatis.heima.controller.Empcontroller
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: on

#mvc:
#  format:
#    date-time: yyyy-MM-dd HH:mm:ss